In [1]:
import numpy as np
import pandas as pd

In [2]:
pos1 = pd.read_csv(r"/media/olehryz/Elements/progs/univ_codes/2025_2026/cel-mech/01-data/1.csv")
pos2 = pd.read_csv(r"/media/olehryz/Elements/progs/univ_codes/2025_2026/cel-mech/01-data/2.csv")
mass = pd.read_csv(r"/media/olehryz/Elements/progs/univ_codes/2025_2026/cel-mech/01-data/mass.csv")

### Acquiring databases

In [3]:
pos1

planet          X          Y         Z        VX        VY            VZ
0  Mercury   0.151658  -0.419266 -0.048173  0.020819  0.010992 -1.011215e-03
1    Venus  -0.687483   0.206739  0.042508 -0.005924 -0.019462  7.442097e-05
2    Earth   0.874787   0.474741 -0.000033 -0.008485  0.015056 -8.523018e-07
3     Mars  -0.664417  -1.362122 -0.012252  0.013106 -0.004934 -4.247716e-04
4  Jupiter  -1.172568   5.051730  0.005250 -0.007445 -0.001354  1.721988e-04
5   Saturn   9.532013  -0.137485 -0.377034 -0.000232  0.005567 -8.771842e-05
6     Uran  10.122594  16.669764 -0.069345 -0.003398  0.001859  5.096477e-05
7  Neptune  29.877098   0.294748 -0.694563 -0.000058  0.003158 -6.371042e-05

In [4]:
pos2

planet          X          Y         Z        VX        VY        VZ
0  Mercury  -0.292446  -0.346321 -0.001485  0.015788 -0.016851 -0.002825
1    Venus  -0.630153  -0.351559  0.031524  0.009713 -0.017757 -0.000805
2    Earth   0.877199   0.470411 -0.000038 -0.008411  0.015097 -0.000001
3     Mars  -1.182557   1.156756  0.053233 -0.009260 -0.008810  0.000042
4  Jupiter  -2.271629  -4.848317  0.070977  0.006749 -0.002853 -0.000139
5   Saturn   4.024448   8.125998 -0.301610 -0.005295  0.002464  0.000168
6     Uran   3.390256  18.862637  0.026074 -0.003895  0.000510  0.000052
7  Neptune  29.229583   6.012940 -0.797521 -0.000648  0.003092 -0.000049

In [5]:
mass

planet          mass
0  Mercury  3.302000e+23
1    Venus  4.868500e+24
2    Earth  5.972190e+24
3     Mars  6.417100e+23
4  Jupiter  1.898190e+27
5   Saturn  5.683400e+26
6     Uran  8.681300e+25
7  Neptune  1.024090e+26

### Position 1

#### barycentrum determination

In [6]:
xb_1 = np.sum(pos1['X']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
yb_1 = np.sum(pos1['Y']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
zb_1 = np.sum(pos1['Z']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)

print("CM at time 1: ", xb_1, yb_1, zb_1)

CM at time 1:  0.0035969846177577145 0.005543628155752434 -0.00014187196585716534


In [7]:
vxb_1 = np.sum(pos1['VX']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
vyb_1 = np.sum(pos1['VY']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
vzb_1 = np.sum(pos1['VZ']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)

print("Velocity of the CM at time 1: ", vxb_1, vyb_1, vzb_1)

Velocity of the CM at time 1:  -7.378695776203276e-06 5.417315236988446e-07 1.3853195030682886e-07


In [8]:
rb = np.array([xb_1, yb_1, zb_1])
vb = np.array([vxb_1, vyb_1, vzb_1])

rb

array([ 0.00359698,  0.00554363, -0.00014187])

In [23]:
vb

array([-7.37869578e-06,  5.41731524e-07,  1.38531950e-07])

#### Shifting to barycentrum coordinates 

In [11]:
r1 = pos1[['X','Y','Z']].to_numpy()
v1 = pos1[['VX','VY','VZ']].to_numpy()

r1_cm = r1 - rb
v1_cm = v1 - vb

v1_cm

array([[ 2.08264090e-02,  1.09915434e-02, -1.01135376e-03],
       [-5.91625182e-03, -1.94621571e-02,  7.42824379e-05],
       [-8.47806846e-03,  1.50559301e-02, -9.90833723e-07],
       [ 1.31130919e-02, -4.93440262e-03, -4.24910129e-04],
       [-7.43783871e-03, -1.35455157e-03,  1.72060281e-04],
       [-2.24602667e-04,  5.56625363e-03, -8.78569563e-05],
       [-3.39078887e-03,  1.85807512e-03,  5.08262422e-05],
       [-5.10415878e-05,  3.15760030e-03, -6.38489522e-05]])

#### Angular momentum determinantion

In [16]:
m = mass['mass'].to_numpy()   

L = m[:, None] * np.cross(r1_cm, v1_cm)

L_total = np.sum(L, axis=0) + 1.98e30 * np.cross(-rb, -vb) 

L_total

array([3.17519043e+24, 1.00613502e+24, 1.20868015e+26])

### Position 2

In [17]:
xb_2 = np.sum(pos2['X']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
yb_2 = np.sum(pos2['Y']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
zb_2 = np.sum(pos2['Z']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)

print("CM at time 2: ", xb_2, yb_2, zb_2)

CM at time 2:  0.0006376652775339225 -0.0011750181764799135 -5.8462304696895295e-05


In [18]:
vxb_2 = np.sum(pos2['VX']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
vyb_2 = np.sum(pos2['VY']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)
vzb_2 = np.sum(pos2['VZ']*mass['mass'])/(np.sum(mass['mass']) + 1.98e30)

print("Velocity of the CM at time 2: ", vxb_2, vyb_2, vzb_2)

Velocity of the CM at time 2:  4.737436284831133e-06 -1.8472543708884877e-06 -8.769447973559408e-08


In [19]:
rb2 = np.array([xb_2, yb_2, zb_2])
vb2 = np.array([vxb_2, vyb_2, vzb_2])

rb2

array([ 6.37665278e-04, -1.17501818e-03, -5.84623047e-05])

In [20]:
r2 = pos2[['X','Y','Z']].to_numpy()
v2 = pos2[['VX','VY','VZ']].to_numpy()

r2_cm = r2 - rb2
v2_cm = v2 - vb2

v2_cm

array([[ 1.57831587e-02, -1.68494920e-02, -2.82503200e-03],
       [ 9.70849631e-03, -1.77548677e-02, -8.04499558e-04],
       [-8.41572972e-03,  1.50988095e-02, -9.19890066e-07],
       [-9.26460227e-03, -8.80799692e-03,  4.24439180e-05],
       [ 6.74402675e-03, -2.85159430e-03, -1.39046340e-04],
       [-5.29989580e-03,  2.46604707e-03,  1.68142054e-04],
       [-3.89999688e-03,  5.11910950e-04,  5.24095735e-05],
       [-6.53057568e-04,  3.09340882e-03, -4.86538951e-05]])

In [22]:
m = mass['mass'].to_numpy()   

L = m[:, None] * np.cross(r2_cm, v2_cm)

L_total2 = np.sum(L, axis=0) + 1.98e30 * np.cross(-rb2, -vb2) 

L_total2

array([3.17519717e+24, 1.00614114e+24, 1.20868316e+26])

### Nachylenie Jowisza do płaszczyzny niezmienniczej

In [27]:
L_JUP = m[4] * np.cross(r2_cm[4, :], v2_cm[4, :])

L_JUP

array([1.66384415e+24, 3.09626198e+23, 7.43498979e+25])

In [28]:
L_total2

array([3.17519717e+24, 1.00614114e+24, 1.20868316e+26])

In [33]:
np.arccos(np.dot(L_JUP, L_total2)/(np.linalg.norm(L_total2)*np.linalg.norm(L_JUP)))*180/np.pi

0.3261906581052375